#include "mcp-registry.h"
#include "libnetdata/libnetdata.h" // For simple_hash(), etc.
                                   // Assuming D_MCP is a log channel defined elsewhere or part of libnetdata's logging
#include "libnetdata/log/nd_log.h"      // For netdata_log_debug, netdata_log_error
#include <string.h>               // For strcmp
#include <stdbool.h>              // For bool type if not included by other headers

// Includes for tool functions
#include "web/mcp/mcp-tools-execute-function.h"
#include "web/mcp/mcp-tools-list-metadata.h"
#include "web/mcp/mcp-tools-query-metrics.h"
#include "web/mcp/mcp-tools-alert-transitions.h"
#include "web/mcp/mcp-tools-configured-alerts.h"
#include "web/mcp/mcp-tools-weights.h" // Added for weights tools
#include "web/mcp/mcp-tools.h" // For MCP_TOOL_* name constants

#define MCP_PLACEHOLDER_SCHEMA_JSON "{ \"type\": \"object\" }" // Simplified placeholder

// Global static registry
MCP_TOOL_REGISTRY_ENTRY mcp_tools_registry[] = {
    {
        .name = MCP_TOOL_EXECUTE_FUNCTION, // "execute_function"
        .hash = 0,
        .acl = HTTP_ACL_FUNCTIONS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_execute_function,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Execute Netdata Function",
        .description = "Execute live data collection functions on nodes.",
        .input_schema_json = MCP_PLACEHOLDER_SCHEMA_JSON,
        .supports_pagination = true, // Example, adjust based on actual capability
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_METRICS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_metrics_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List available metrics",
        .description = "Search and list available metrics to query, across some or all nodes, for any time-frame.",
        .input_schema_json = NULL, // Placeholder - schema to be generated by mcp_unified_list_tool_schema
        .supports_pagination = false, // Unified list tool does not yet support MCP-level pagination
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_GET_METRICS_DETAILS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_get_metrics_details_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Get metrics details",
        .description = "Get retention and cardinality information about specific metrics.",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_NODES,
        .hash = 0,
        .acl = HTTP_ACL_NODES,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_nodes_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List monitored nodes",
        .description = "Search for and list monitored nodes by hostname patterns.",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_GET_NODES_DETAILS,
        .hash = 0,
        .acl = HTTP_ACL_NODES,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_get_nodes_details_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Get detailed information about monitored nodes",
        .description = "Gets comprehensive node information including hardware specs, OS details, capabilities, health status, available functions, streaming and monitoring configuration.",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_FUNCTIONS,
        .hash = 0,
        .acl = HTTP_ACL_FUNCTIONS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_functions_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List available functions",
        .description = "List available Netdata functions that can be executed on specific nodes.",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_RAISED_ALERTS,
        .hash = 0,
        .acl = HTTP_ACL_ALERTS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_raised_alerts_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List raised alerts",
        .description = "List currently active alerts (WARNING and CRITICAL status).",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_ALL_ALERTS,
        .hash = 0,
        .acl = HTTP_ACL_ALERTS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_all_alerts_job,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List all alerts",
        .description = "List all currently running alerts.",
        .input_schema_json = NULL,
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_QUERY_METRICS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_query_metrics,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Query Metrics Data",
        .description = "Query time-series metrics data with filtering, aggregation, and grouping.",
        .input_schema_json = NULL, // Placeholder for now
        .supports_pagination = false, // Uses time-based windowing
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_ALERT_TRANSITIONS,
        .hash = 0,
        .acl = HTTP_ACL_ALERTS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_alert_transitions,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List alert transitions",
        .description = "List historical alert status changes with filtering options.",
        .input_schema_json = NULL, // Placeholder for now
        .supports_pagination = true, // Has a 'cursor' param
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_LIST_CONFIGURED_ALERTS,
        .hash = 0,
        .acl = HTTP_ACL_ALERTS,
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_list_configured_alerts,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "List configured alerts",
        .description = "Lists all configured alert prototypes in the system.",
        .input_schema_json = "{\"type\": \"object\", \"properties\": {}}", // No parameters
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_FIND_CORRELATED_METRICS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS, // Consider a more specific ACL if available, e.g., HTTP_ACL_ANOMALY_DETECTION or HTTP_ACL_ML
        .access = HTTP_ACCESS_ANONYMOUS_DATA, // Or more restrictive if needed
        .execute = mcp_tool_find_correlated_metrics,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Find metrics that changed during an incident",
        .description = "Compares metric behavior between a query window and a baseline to find correlations.",
        .input_schema_json = NULL, // Placeholder - schema defined by mcp_tool_find_correlated_metrics_schema
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_FIND_ANOMALOUS_METRICS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS, // HTTP_ACL_ANOMALY_DETECTION or HTTP_ACL_ML
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_find_anomalous_metrics,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Find metrics with highest anomaly rates",
        .description = "Identifies metrics that exhibited the most anomalous behavior during a specified time window.",
        .input_schema_json = NULL, // Placeholder - schema defined by mcp_tool_find_anomalous_metrics_schema
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    {
        .name = MCP_TOOL_FIND_UNSTABLE_METRICS,
        .hash = 0,
        .acl = HTTP_ACL_METRICS, // HTTP_ACL_ANOMALY_DETECTION or HTTP_ACL_ML
        .access = HTTP_ACCESS_ANONYMOUS_DATA,
        .execute = mcp_tool_find_unstable_metrics,
        .namespace = MCP_NAMESPACE_TOOLS,
        .title = "Find metrics with high variability",
        .description = "Identifies metrics that exhibited high variability or instability during a specified time window using coefficient of variation.",
        .input_schema_json = NULL, // Placeholder - schema defined by mcp_tool_find_unstable_metrics_schema
        .supports_pagination = false,
        .supports_streaming = false,
        .cacheable_schema = true,
        .schema_cache_duration = 3600,
    },
    { .name = NULL } // Terminator
};

// It's good practice to define log domains if they are not globally available
#ifndef D_MCP
#define D_MCP ND_LOG_CAT_USER
#warning "Log channel D_MCP not defined, defaulting to ND_LOG_CAT_USER. Please define it in a relevant header."
#endif


void mcp_tools_registry_init(void) {
    for (MCP_TOOL_REGISTRY_ENTRY *tool = mcp_tools_registry; tool->name != NULL; tool++) {
        if (tool->hash == 0) { // Calculate hash if not pre-set
            tool->hash = simple_hash(tool->name);
        }
        netdata_log_debug(D_MCP, "MCP Tool '%s' initialized with hash %u", tool->name, tool->hash);
    }
}

const MCP_TOOL_REGISTRY_ENTRY *mcp_find_tool(const char *tool_name) {
    if (!tool_name || !*tool_name) {
        return NULL;
    }

    uint32_t hash = simple_hash(tool_name);
    for (MCP_TOOL_REGISTRY_ENTRY *tool = mcp_tools_registry; tool->name != NULL; tool++) {
        // Check hash first for performance, then strcmp to resolve collisions
        if (tool->hash == hash && strcmp(tool->name, tool_name) == 0) {
            return tool;
        }
    }
    netdata_log_debug(D_MCP, "MCP Tool '%s' not found in registry.", tool_name);
    return NULL;
}

// Placeholder for mcp_tool_execute_function is now removed, as we link to the real one.
// int mcp_tool_execute_function(struct mcp_req_job *job) {
//     (void)job; // Suppress unused parameter warning
//     netdata_log_error(D_MCP, "MCP: mcp_tool_execute_function is not yet implemented.");
//     return -1;
// }

// mcp_get_tools_by_namespace will be implemented later
const MCP_TOOL_REGISTRY_ENTRY **mcp_get_tools_by_namespace(MCP_NAMESPACE namespace, size_t *count) {
    (void)namespace; // Suppress unused parameter warning
    if (!count) return NULL; // Basic error checking

    netdata_log_error(D_MCP, "MCP: mcp_get_tools_by_namespace is not yet implemented.");
    *count = 0;
    // This function would typically iterate through mcp_tools_registry,
    // collect all entries matching the namespace, allocate an array to hold pointers to them,
    // and return that array, setting *count to the number of tools found.
    // The caller would be responsible for freeing the returned array.
    return NULL;
}
